language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

dist: xenial

install:
  - "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python"
  - "poetry config virtualenvs.create false"
  - "poetry install --no-interaction --no-ansi"

cache: pip

script: tox
